namespace TestTools.Services
{
    public class RandomAddressGenerator
    {
        private static string[] address = {
            "FRONDEG HEOL MISKIN PONTYCLUN CF72 9AJ",
            "BPU RADNOR HOUSE GREENWOOD CLOSE CARDIFF CF23 8AA",
            "66 CORPORATION ROAD CARDIFF CF11 7AW",
            "1 HEATHWOOD ROAD CARDIFF CF14 4JL",
            "9 PANTYGRAIGWEN ROAD PONTYPRIDD CF37 2RR",
            "9A BRIDGEND BUSINESS CENTRE BENNETT STREET BRIDGEND CF31 3SH",
            "2 WAUN HIR PONTYPRIDD CF38 1AX",
            "28 WINDSOR PLACE CARDIFF CF10 3SG",
            "37 FITZHAMON EMBANKMENT CARDIFF CF11 6AN",
            "18 COLLEGE STREET ABERDARE CF44 0RN",
            "7 VENTURE WALES BUILDING DEPOT ROAD ABERDARE CF44 8DL",
            "1 HEOL-YR-YSBYTY CAERPHILLY CF83 1TA",
            "14 STONECHAT CLOSE PORTHCAWL CF36 3QF",
            "2 THURSTON STREET CARDIFF CF5 1PN",
            "2 COBURN STREET CARDIFF CF24 4BS",
            "56 HEOL AMLWCH CARDIFF CF14 2PT",
            "7 VILLA HOUSE HERBERT TERRACE PENARTH CF64 2AH",
            "7 DEPOT ROAD ABERDARE CF44 8DL",
            "44 GLOUCESTER STREET ABERDARE CF44 7BP",
            "36 GRAIG ROAD PORTH CF39 0NS",
            "8 TONYPANDY ENTERPRISE PARK LLWYNYPIA ROAD TONYPANDY CF40 2ET",
            "55 SEAWAY HOUSE BUTE STREET CARDIFF CF10 5AH",
            "19-19A STATION ROAD CARDIFF CF14 5LS",
            "10 HILLSIDE DRIVE CARDIFF CF71 7EA",
            "GARTH VIEW HIGH STREET CAERPHILLY CF83 8FT",
            "34 HEOL WAUN Y NANT CARDIFF CF14 1JZ",
            "71 PROSPECT HOUSE HIGH STREET COWBRIDGE CF71 7AF",
            "71 HIGH STREET COWBRIDGE CF71 7AF",
            "60 THE PAVILION EASTGATE COWBRIDGE CF71 7AB",
            "5 CARLTON HOUSE HERBERT TERRACE PENARTH CF64 2AH",
            "48 PARTRIDGE ROAD CARDIFF CF24 3QX",
            "57 ILAN ROAD CAERPHILLY CF83 4DZ",
            "44B VICTORIA ROAD PENARTH CF64 3HY",
            "4 PENCERRIG RISE HEOLGERRIG MERTHYR TYDFIL CF48 1BF",
            "183 LANSDOWNE ROAD CARDIFF CF5 1JQ",
            "35 PONTCANNA STREET CARDIFF CF11 9HQ",
            "1 SOUTH TERRACE MERTHYR TYDFIL CF48 2RL",
            "42 BRIDGEND ROAD BRIDGEND CF32 9BA",
            "22 ASHDALE ROAD TONYPANDY CF40 1RT",
            "5 GLEBE STREET PENARTH CF64 1EE",
            "MILL LODGE WINDMILL CLOSE COWBRIDGE CF71 7QU",
            "6 BURNABY STREET CARDIFF CF24 2JW",
            "79 BRYNTIRION HILL BRIDGEND CF31 4BY",
            "24 MILDRED STREET PONTYPRIDD CF38 2AW",
            "UNIT G1 CAERPHILLY BUSINESS PARK VAN ROAD CAERPHILLY CF83 3ED",
            "493 CAERPHILLY ROAD CARDIFF CF14 4SN",
            "CELTIC HOUSE CAXTON PLACE CARDIFF CF23 8HA",
            "4 GODWIN CLOSE CARDIFF CF5 2PF",
            "7 GELLIWASTAD ROAD PONTYPRIDD CF37 2BP",
            "1 ARCHER ROAD PENARTH CF64 3HW",
            "24 BARRY ROAD BARRY CF63 1BA",
            "BALTIC HOUSE MOUNT STUART SQUARE CARDIFF CF1 6DH",
            "124 CATHEDRAL ROAD CARDIFF CF1 9LQ"
        };

        public static string Generate()
        {
            var random = new System.Random(System.Guid.NewGuid().GetHashCode());
            int index = random.Next(address.Length);
            return address[index];
        }
    }
}
